spring.application.name=tco-calculator
spring.jpa.hibernate.ddl-auto=validate

# Use host.docker.internal to reach the sibling Postgres container via the host gateway
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret